name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: python-docker  # Add the environment name

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub securely using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Shorten commit SHA using shell command
      - name: Get short commit SHA
        id: short_sha
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | head -c 8)" >> $GITHUB_ENV

      # Step 5: Get the current date and time in UTC format
      - name: Get date and time
        id: date_time
        run: echo "DATE_TIME=$(date -u +'%Y-%m-%dT%H-%M-%SZ')" >> $GITHUB_ENV

      # Step 6: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            sachinfe/app:latest
            sachinfe/app:${{ github.ref_name }}
            sachinfe/app:${{ env.SHORT_SHA }}
            sachinfe/app:${{ github.ref_name }}-${{ env.DATE_TIME }}
